likablehair/svelte

- src/lib/common/scroller.ts
- src/lib/dates/Calendar.svelte
- src/lib/dates/DatePicker.svelte
- src/lib/dates/utils.ts
- src/routes/dates/DatePicker.svelte
- src/routes/index.svelte
Date Picker creato, manca il locate per la formattazione delle date
> COMP-17: date picker

- src/lib/components/simple/dates/DatePicker.css
- src/lib/components/simple/dates/DatePicker.svelte
- src/lib/components/simple/dates/DatePickerTextField.svelte
- src/routes/docs/components/simple-components/DatePickerTextField/+page.svelte
Corretto funzionamento per la visualizzazione della maschera della data iniziale
> COMP-35 fix date picker mask

- src/lib/components/simple/common/Card.svelte
- src/lib/components/simple/common/Menu.svelte
- src/routes/docs/components/simple-components/Dialog/+page.svelte
Ho sistemato la posizione del menu nel caso in cui il menu sia inserito nel parente absolute/fixed-flex
> COMP-37 FIX MENU POSITION

- src/lib/components/layouts/UnstableDividedSideBarLayout.svelte
- src/lib/components/simple/forms/Autocomplete.svelte
- src/lib/components/simple/forms/FileInput.css
- src/lib/components/simple/forms/FileInput.svelte
- src/lib/components/simple/forms/FileInputList.css
- src/lib/components/simple/forms/FileInputList.svelte
- src/routes/docs/components/simple-components/Autocomplete/+page.svelte
- src/routes/docs/components/simple-components/FileInput/+page.svelte
- src/routes/docs/components/simple-components/FileInputList/+page.svelte
- src/routes/docs/search/components.database.ts
1. aggiornato il componente FileInput, aggiunto .css relativo e aggiunta la pagina relativa in /docs  
2. aggiornato comportamento del Autocomplete. Ora si chiude dopo la selezione
> fix FileInput component

- src/lib/components/composed/forms/DatePickerTextField.svelte
- src/lib/components/layouts/UnstableDividedSideBarLayout.svelte
Esteso il range accettabile di anni nel DatePickerTextField da 1970-2030 a 1970-2100 #31
> Fix date picker textfield #31

- src/lib/components/layouts/CollapsibleSideBarLayout.svelte
Aggiunta della gestione evento on:menu-select per le voci dell'header sul menu da telefono
> Add on:select event on Header Mobile menu

- src/lib/components/simple/lists/SelectableVerticalList.svelte
- src/routes/docs/components/composed-components/MenuOrDrawerOptions/+page.svelte
Add field disabled on SelectableVerticalList
> DUEDIL-246 - added disabled options on list element

- src/lib/components/composed/search/Filters.css
- src/lib/components/composed/search/Filters.svelte
Aggiunta di variabili di colori (default e modificabili) per la corretta visualizzazione dei colori dei filtri
> filter button cancel - color & background color

- src/lib/components/layouts/UnstableDividedSideBarLayout.svelte
- src/lib/components/simple/lists/ColorInvertedSelector.svelte
- src/routes/docs/components/composed-components/PaginatedTable/+page.svelte
- src/routes/docs/components/layouts/UnstableDividedSideBarLayout/+page@.svelte
Aggiunto slot per inserire del codice prima o dopo l'icona del componente UnstableDividedSidebarLayout
> DUEDIL-610

- src/lib/components/composed/list/PaginatedTable.svelte
ho passato il filterbuilder alla pagina anche quando viene fatto il sort
> COMP-48 passing filterbuilder when sorted

- src/lib/components/composed/list/PaginatedTable.svelte
> Comp 48 bugfiltersbuilder

- src/lib/components/simple/forms/RadioButton.css
- src/lib/components/simple/forms/RadioButton.svelte
- src/routes/docs/components/simple-components/RadioButton/+page.svelte
- src/routes/docs/search/components.database.ts
ho aggiunto il componente radiobutton in src/lib/components/simple/forms
> COMP-20 radio button component added

- src/lib/components/simple/forms/RadioButton.css
- src/lib/components/simple/forms/RadioButton.svelte
- src/lib/components/simple/lists/SimpleTable.svelte
c'era un console log fastidioso nella simple table
> removed a console log

- src/lib/components/composed/forms/AsyncAutocomplete.svelte
esportati slots nell'async autocomplete
> fix async autocomplete

- src/lib/components/composed/list/DynamicTable.svelte
- src/lib/components/simple/common/InfiniteScroll.svelte
- src/routes/docs/components/composed-components/DynamicTable/+page.svelte
nel primo commit ho fatto in modo tale che se c'e' una riga con i subItems mostrati, l'header della sottotabella rimane sotto l'header della tabella padre
nel secondo commit ho fatto in modo che quando vengono caricate altre righe, "cancella" le righe sopra, renderizzando sempre lo stesso numero di <tr>
> Fix header dynamic table

- package-lock.json
- src/lib/components/composed/forms/AvatarDropdown.svelte
- src/lib/components/composed/list/DynamicTable.css
- src/lib/components/composed/list/DynamicTable.svelte
- src/lib/components/simple/forms/Autocomplete.svelte
- src/lib/components/simple/media/Icon.svelte
- src/lib/components/simple/navigation/Chip.svelte
- src/lib/css/main.css
rimossi i button nestati in giro per la libreria, aggiustata l'autocomplete che quando flippata non rimaneva attaccata alla textfield
> fix generali

- src/lib/components/composed/list/DynamicTable.svelte
questa pull l'ho aperta quando in master c'era ancora la versione 4 di svelte e nel branch della versione 5 di svelte questa modifica e' gia' stata effettuata
> fix scroll

- src/lib/components/composed/list/DynamicTable.svelte
aggiustato lo sticky del subheader della dynamic table
> Comp 81 svelte 5

- src/lib/components/composed/list/PaginatedTable.svelte
Modificato il comportamento della barra di ricerca e dei filtri su schermi con diverse dimensioni.
> ADDIBOX-690 fix paginated table

- src/lib/components/composed/list/DynamicTable.css
- src/lib/components/composed/list/DynamicTable.svelte
- src/routes/docs/components/composed-components/DynamicTable/+page.svelte
Aggiunte variabili CSS per personalizzare la DynamicTable
> COMP-94 refactor DynamicTable styles - svelte 5
